### ISSUE TITLE
Remove downloaded patch files after successful patching.

### ISSUE THREAD

**Issue by dalgibbard** [dalgibbard/citrix_xenserver_patcher#22]
* Files are downloaded from Citrix in .zip format. These are decompressed, and the .zip version deleted.
* After patching, the non-compressed patch files still remain...
* A flag for ```--no-delete``` or ```-d``` or something should be made available for stopping this deletion process.

**Comment by sjkeerthi** [comment]
This is about the deleting the the downloaded zip file. I am considering about once the patch installed you can see the /var/patch will occupies some space of disk.

Should consider to have options as --cleanpatch this should work as xe patch-clean command in backed.

**Comment by dsiminiuk** [comment]
I solved this another way.

create a file in /etc/cron.daily
call it clean-var-patch
it contains

```#!/bin/bash
/usr/bin/find /var/patch/*-*-*-* -mtime +1 -exec rm {} \;
```

And let the cleanup happen by itself.

**Comment by dalgibbard** [comment]
Tested this in the new code; works well. Both src packages and /var/patch files are cleaned after each patch is successfully deployed. ```-C``` flag has been made available to disable the cleaning actions.

The only caveat is that the patch-clean command doesn't apply to pool slaves in a pool scenario; but that's a small price to pay really.

Will close this once i've committed my changes.
