### ISSUE TITLE
Old patches?

### ISSUE THREAD

**Issue by Zuko** [dalgibbard/citrix_xenserver_patcher#32]
Why patcher tries to install "installed" patches?
xe patch-list:

    xe patch-list
    uuid ( RO): 4fc82e62-b938-407d-a2c6-68c8922f3ec2
      name-label ( RO): XS62ESP1014
    name-description ( RO): Public Availability: security fixes to bash
    size ( RO): 1851360
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): f4f66d0a-d408-446e-a014-8e793baccb07
      name-label ( RO): XS62ESP1015
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 18577686
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 1e11bede-e41f-402e-879b-1210fa779a68
      name-label ( RO): XS62E007
    name-description ( RO): ioemu fixes for Windows 8.1
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 0850b186-4d47-11e3-a720-001b2151a503
      name-label ( RO): XS62ESP1
    name-description ( RO): Public Availability: XenServer 6.2 Service Pack 1 (SP1)
    size ( RO): 218600009
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 1c952800-c030-481c-a0c1-d1b45aa19fcc
      name-label ( RO): XS62ESP1005
    name-description ( RO): Public Availability: fixes to Dom0 kernel
    size ( RO): 37787132
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): aeff92a9-2c60-43eb-b34e-14e4132b411c
      name-label ( RO): XS62E005
    name-description ( RO): Public Availability: Toolstack fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): 3c291f5f-103f-4c83-af64-353399c3defc
      name-label ( RO): XS62ESP1006
    name-description ( RO): Fix to Toolstack
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): d9c753b9-a15b-4a31-897b-97fdae609031
      name-label ( RO): XS62E009
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): ff202d2d-2812-4c6b-b500-2f4701de7bc4
      name-label ( RO): XS62E011
    name-description ( RO): Public Availability: Storage and ISCSI fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 5579f1f0-ff83-11e2-b778-0800200c9a66
      name-label ( RO): XS62E004
    name-description ( RO): Public Availability: Fixes for Dom0 kernel issues
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): c8b9d332-30e4-4e5e-9a2a-8aaae6dee91a
      name-label ( RO): XS62E015
    name-description ( RO): Public Availability: XenTools fixes
    size ( RO): 115564441
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): d51db8df-0bde-48e8-93ab-bcc23971f1a9
      name-label ( RO): XS62E017
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 297f2f77-5603-4aaf-9e56-db49512d4592
      name-label ( RO): XS62ESP1002
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 1744985
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 83bca9f6-4ae5-45f9-9426-440216f73797
      name-label ( RO): XS62E010
    name-description ( RO): Public Availability: Fix for GPU pass through
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): 
    
    
    uuid ( RO): a4251789-ce6c-4726-942c-3cddbadcaca6
      name-label ( RO): XS62E012
    name-description ( RO): Public Availability: Fixes for Dom0 kernel issues
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 78251ea4-e4e7-4d72-85bd-b22bc137e20b
      name-label ( RO): XS62E014
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 996dd2e7-ad95-49cc-a0be-2c9adc4dfb0b
      name-label ( RO): XS62ESP1004
    name-description ( RO): Public Availability: Fixes to Toolstack, Xen and improved interface with Citrix CloudPlatform
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 7d670435-547c-419a-ab7e-296705a752b8
      name-label ( RO): XS62ESP1011
    name-description ( RO): Public Availability: Toolstack, vGPU and Xen fixes
    size ( RO): 18575598
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): dedcc0dd-d8f3-4f76-90ca-92697c7a44f0
      name-label ( RO): XS62E001
    name-description ( RO): Public Availability: Xapi fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): b22d6335-823d-43a6-ba26-28793717125b
      name-label ( RO): XS62ESP1013
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 18576306
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 7d5a3a2f-e163-4f23-b8f7-929961eeeb2e
      name-label ( RO): XS62E008
    name-description ( RO): XenTools fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): 53546429-4c4f-4e8a-ac11-b680aadab046
      name-label ( RO): XS62ESP1007
    name-description ( RO): Public Availability: Storage Security fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): 59a75271-12f9-4e6a-8ba2-325c2f5b0b47
      name-label ( RO): XS62ESP1008
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 16584550
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): c208dc56-36c2-4e91-b8d7-0246575b1828
      name-label ( RO): XS62ESP1003
    name-description ( RO): Public Availability: XenTools fixes
    size ( RO): 115563025
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): 8b0518d8-3610-4b7f-8a31-0e02718d2f9f
      name-label ( RO): XS62E013
    name-description ( RO): Limited Availability: Toolstack fixes
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartXAPI
    
    
    uuid ( RO): 59128f15-92cd-4dd9-8fbe-a0115d1b07a2
      name-label ( RO): XS62E002
    name-description ( RO): Public Availability: security fixes to Xen
    size ( RO): 0
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
    
    uuid ( RO): a24d94e1-326b-4eaa-8611-548a1b5f8bd5
      name-label ( RO): XS62ESP1009
    name-description ( RO): Public Availability: fixes to Dom0 kernel
    size ( RO): 37800751
       hosts (SRO): f64355c6-1a19-408e-ac33-e248b66c953d, db6ac00d-2eed-48ce-9474-4e92f2128ff6
    after-apply-guidance (SRO): restartHost
    
./patcher.py -e ./XS62_exclusions.py:

    No local Patches are installed.
    The following Patches are pending installation:
    
    uuid: 0850b186-4d47-11e3-a720-001b2151a503
     url: http://support.citrix.com/article/CTX139788
     timestamp: 2013-12-16T00:00:00Z
     name_label: XS62ESP1
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/8707/XS62ESP1.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: XenServer 6.2 Service Pack 1 (SP1)
     
    uuid: 297f2f77-5603-4aaf-9e56-db49512d4592
     url: http://support.citrix.com/article/CTX140051
     timestamp: 2014-01-22T00:00:00Z
     name_label: XS62ESP1002
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/8737/XS62ESP1002.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: security fixes to Xen
     
    uuid: c208dc56-36c2-4e91-b8d7-0246575b1828
     url: http://support.citrix.com/article/CTX140416
     timestamp: 2014-03-26T00:00:00Z
     name_label: XS62ESP1003
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/9031/XS62ESP1003.zip
     after_apply_guidance: restartXAPI
     name_description: Public Availability: XenTools fixes
     
    uuid: 1c952800-c030-481c-a0c1-d1b45aa19fcc
     url: http://support.citrix.com/article/CTX140553
     timestamp: 2014-04-28T00:00:00Z
     name_label: XS62ESP1005
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/9058/XS62ESP1005.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: fixes to Dom0 kernel
     
    uuid: c8b9d332-30e4-4e5e-9a2a-8aaae6dee91a
     url: http://support.citrix.com/article/CTX140808
     timestamp: 2014-05-28T00:00:00Z
     name_label: XS62E015
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/9279/XS62E015.zip
     after_apply_guidance: restartXAPI
     name_description: Public Availability: XenTools fixes
     
    uuid: 59a75271-12f9-4e6a-8ba2-325c2f5b0b47
     url: http://support.citrix.com/article/CTX141036
     timestamp: 2014-07-16T00:00:00Z
     name_label: XS62ESP1008
     patch_url: http://downloadns.citrix.com.edgesuite.net/akdlm/9491/XS62ESP1008.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: security fixes to Xen
     
    uuid: a24d94e1-326b-4eaa-8611-548a1b5f8bd5
     url: http://support.citrix.com/article/CTX141191
     timestamp: 2014-08-27T00:00:00Z
     name_label: XS62ESP1009
     patch_url: http://downloadns.citrix.com.edgesuite.net/9617/XS62ESP1009.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: fixes to Dom0 kernel
     
    uuid: 7d670435-547c-419a-ab7e-296705a752b8
     url: http://support.citrix.com/article/CTX141472
     timestamp: 2014-09-30T00:00:00Z
     name_label: XS62ESP1011
     patch_url: http://downloadns.citrix.com.edgesuite.net/9698/XS62ESP1011.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: Toolstack
     vGPU and Xen fixes
     
    uuid: b22d6335-823d-43a6-ba26-28793717125b
     url: http://support.citrix.com/article/CTX141480
     timestamp: 2014-10-01T00:00:00Z
     name_label: XS62ESP1013
     patch_url: http://downloadns.citrix.com.edgesuite.net/9703/XS62ESP1013.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: security fixes to Xen
     
    uuid: 4fc82e62-b938-407d-a2c6-68c8922f3ec2
     url: http://support.citrix.com/article/CTX141486
     timestamp: 2014-10-09T00:00:00Z
     name_label: XS62ESP1014
     patch_url: http://downloadns.citrix.com.edgesuite.net/9708/XS62ESP1014.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: security fixes to bash
     
    uuid: f4f66d0a-d408-446e-a014-8e793baccb07
     url: http://support.citrix.com/article/CTX141717
     timestamp: 2014-12-03T00:00:00Z
     name_label: XS62ESP1015
     patch_url: http://downloadns.citrix.com.edgesuite.net/10128/XS62ESP1015.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: security fixes to Xen
     
    uuid: a26964cf-a409-46a4-b94c-66bf6083690f
     url: http://support.citrix.com/article/CTX141845
     timestamp: 2014-12-21T00:00:00Z
     name_label: XS62ESP1012
     patch_url: http://downloadns.citrix.com.edgesuite.net/10134/XS62ESP1012.zip
     after_apply_guidance: restartXAPI
     name_description: Public Availability: XenTools fixes
     
    uuid: 55444a02-4d97-4d6d-b076-ddbe8697244b
     url: http://support.citrix.com/article/CTX141779
     timestamp: 2015-01-09T00:00:00Z
     name_label: XS62ESP1016
     patch_url: http://downloadns.citrix.com.edgesuite.net/10174/XS62ESP1016.zip
     after_apply_guidance: restartHost
     name_description: Public Availability: Storage
     Xen and Toolstack fixes
    
    NOTE: Installation of these items will require a reboot!
      You will be prompted to reboot at the end.
    
    
    Would you like to install these items? [y/n]: n
    You didn't want to patch...
    
I have only two patches to install: XS62ESP1012 and XS62ESP1016 not all of them ;/

**Comment by dalgibbard** [comment]
Just some initial feedback; it's likely caused by the host being a member of a pool. It's not a configuration I've used/tested personally and likely requires that we find a permanent fix for host UUID detection too.
Are you running the script on the pool master? Have you tried running it with the required pool flags?

**Comment by Zuko** [comment]
I tried on pool master and on pool member, same results.

**Comment by Zuko** [comment]
Thanks for suggestion (-p option). This solves my problem ;)
Have a nice day ;-)

**Comment by dalgibbard** [comment]
I'll reopen this anyway, as this needs to be pointed out in the documentation :)

**Comment by yaffeweb** [comment]
Since we are on the topic of old patches, how possible is it to just have the script remove the tar.bz2 file upon installation completion? I noticed it removes the xsupdate and the zip but leaves behind the other file which only allows so many before you have to delete them manually because of disk space.

**Comment by dalgibbard** [comment]
@yaffeweb - #22

**Comment by yaffeweb** [comment]
obviously I can't read.. Thanks for the issue link!

**Comment by dalgibbard** [comment]
Nps :D
