### ISSUE TITLE
Xenserver 6.5 support?

### ISSUE THREAD

**Issue by symgryph** [dalgibbard/citrix_xenserver_patcher#34]
Was wondering if this would work with xenserver 6.5?

**Comment by dalgibbard** [comment]
I've not tested it directly; but I also don't see any updates for 6.5 in the XML feed yet, so we won't truely know until they release a patch (assuming they haven't)  :)

**Comment by gladston3** [comment]
They released a patch now. What do I have to do to test it/make it work?

Thx in advance

**Comment by sjkeerthi** [comment]
I tested the code its working on xenserver 6.5.

How to do it.

download the patcher.py on your xenserver under tmp 
wget --no-check-certificate -O patcher.py https://raw.github.com/dalgibbard/citrix_xenserver_patcher/master/patcher.py
chmod +x patcher.py
./patcher.py

Below are my screenshot from xenserver 6.5
====================================
./patcher.py 
Getting host list using: /opt/xensource/bin/xe host-list name-label=`grep "^HOSTNAME=" /etc/sysconfig/network | awk -F= '{print$2}'` params=uuid --minimal
Detected HOST UUID: 180f8b5a-d232-458a-ab44-05a282de8e27
Get patch list using: /opt/xensource/bin/xe patch-list hosts="180f8b5a-d232-458a-ab44-05a282de8e27" --minimal
The following Patches are pending installation:

uuid: 5200911d-5f79-4149-abca-0556af77b14d
 url: http://support.citrix.com/article/CTX142061
 timestamp: 2015-02-18T00:00:00Z
 name_label: XS65E003
 patch_url: http://downloadns.citrix.com.edgesuite.net/10196/XS65E003.zip
 after_apply_guidance: restartHost
 name_description: Public Availability: security fixes to glibc
 
uuid: 492ca007-bf7b-454f-8e5c-63a991a52449
 url: http://support.citrix.com/article/CTX142141
 timestamp: 2015-03-03T00:00:00Z
 name_label: XS65E005
 patch_url: http://downloadns.citrix.com.edgesuite.net/10201/XS65E005.zip
 after_apply_guidance: 
 name_description: Public Availability: Storage fixes to prevent disk corruption
 
uuid: 30d3992b-ac0a-45e8-9e93-d4b2e9bb235f
 url: http://support.citrix.com/article/CTX142147
 timestamp: 2015-03-11T00:00:00Z
 name_label: XS65E006
 patch_url: http://downloadns.citrix.com.edgesuite.net/10207/XS65E006.zip
 after_apply_guidance: restartHost
 name_description: Public Availability: security fixes to Xen
 
uuid: d3c08fcb-daa0-4410-bdb2-c298109e88ad
 url: http://support.citrix.com/article/CTX142266
 timestamp: 2015-04-08T00:00:00Z
 name_label: XS65E008
 patch_url: http://downloadns.citrix.com.edgesuite.net/10320/XS65E008.zip
 after_apply_guidance: restartHost
 name_description: Public Availability: Fix for Dom0 kernel

NOTE: Installation of these items will require a reboot!
      You will be prompted to reboot at the end.


Would you like to install these items? [y/n]: y

Starting patching...
Downloading: XS65E003.zip
Download Size: 31742971 Bytes
   31742971  [100.00%]
Applying: XS65E003
Uncompressing...
Internal Upload...
Completed: 5200911d-5f79-4149-abca-0556af77b14d

Applying Patch 5200911d-5f79-4149-abca-0556af77b14d
/opt/xensource/bin/xe patch-apply uuid=5200911d-5f79-4149-abca-0556af77b14d host-uuid=180f8b5a-d232-458a-ab44-05a282de8e27
Downloading: XS65E005.zip
Download Size: 3316830 Bytes
    3316830  [100.00%]
Applying: XS65E005
Uncompressing...
Internal Upload...
Completed: 492ca007-bf7b-454f-8e5c-63a991a52449

Applying Patch 492ca007-bf7b-454f-8e5c-63a991a52449
/opt/xensource/bin/xe patch-apply uuid=492ca007-bf7b-454f-8e5c-63a991a52449 host-uuid=180f8b5a-d232-458a-ab44-05a282de8e27
Downloading: XS65E006.zip
Download Size: 10675554 Bytes
   10675554  [100.00%]
Applying: XS65E006
Uncompressing...
Internal Upload...
Completed: 30d3992b-ac0a-45e8-9e93-d4b2e9bb235f

Applying Patch 30d3992b-ac0a-45e8-9e93-d4b2e9bb235f
/opt/xensource/bin/xe patch-apply uuid=30d3992b-ac0a-45e8-9e93-d4b2e9bb235f host-uuid=180f8b5a-d232-458a-ab44-05a282de8e27
Downloading: XS65E008.zip
Download Size: 108511340 Bytes
  108511340  [100.00%]
Applying: XS65E008
Uncompressing...
Internal Upload...
Completed: d3c08fcb-daa0-4410-bdb2-c298109e88ad

Applying Patch d3c08fcb-daa0-4410-bdb2-c298109e88ad
/opt/xensource/bin/xe patch-apply uuid=d3c08fcb-daa0-4410-bdb2-c298109e88ad host-uuid=180f8b5a-d232-458a-ab44-05a282de8e27

A reboot is now required. Would you like to reboot now? [y/n]: y
Rebooting...
