### ISSUE TITLE
Fails to install July patches

### ISSUE THREAD

**Issue by kylebrowning** [dalgibbard/citrix_xenserver_patcher#40]
Downloading: XS65E010.zip
Download Size: 14336386 Bytes
   14336386  [100.00%]
Applying: XS65E010
Uncompressing...
Internal Upload...
XE Error detected: The uploaded patch file already exists
uuid: 1a559b8c-6d84-4a5f-b2d6-c8a2eafa2fc6

Return code is: 1
Patch previously uploaded, attempting to reapply 1a559b8c-6d84-4a5f-b2d6-c8a2eafa2fc6
Applying Patch 1a559b8c-6d84-4a5f-b2d6-c8a2eafa2fc6
Patch failed, code: 1
Command failed: /opt/xensource/bin/xe patch-apply uuid=1a559b8c-6d84-4a5f-b2d6-c8a2eafa2fc6 host-uuid=9304e60b-cc9b-4720-97c3-70f48e97c4cd
Failed to apply patch: The patch precheck stage failed: the server is of an incorrect version.
patch: 1a559b8c-6d84-4a5f-b2d6-c8a2eafa2fc6 (XS65E010)
found_version: XS65ESP1 - Public Availability: XenServer 6.5 Service Pack 1 (SP1)
required_version: 6.5

Secondary validation check...
Patch apply failed for: XS65E010.xsupdate

**Comment by kylebrowning** [comment]
Had to exclude XS65E010 locally.

This is from the latest download from citrix.

**Comment by dalgibbard** [comment]
Had a quick look; and the security fixes contained within E010 are mirrored in ESP1004 for XenServer 6.5 SP1, so i'll update the excludes list to include E010.

**Comment by dalgibbard** [comment]
Link to non-SP1 Patch: http://support.citrix.com/article/CTX142537
Link to SP1 Patch: https://support.citrix.com/article/CTX142538
Link to article defining the application fixes: http://support.citrix.com/article/CTX201145

**Comment by dalgibbard** [comment]
Done.

**Comment by kylebrowning** [comment]
Thanks!

**Comment by dalgibbard** [comment]
No problem; thanks for pointing it out!
