### ISSUE TITLE
the url for some of the updates in updates.xml appear to be wrong

### ISSUE THREAD

**Issue by jyork-sarc** [dalgibbard/citrix_xenserver_patcher#41]
I am getting error 404 codes for the XS62ESP1 update. I looked at the url and the one that is provided in the updates.xml file has the URL of 
http://downloadns.citrix.com.edgesuite.net/akdlm/8707/XS62ESP1.zip
However the URL is supposed to be:
http://downloadns.citrix.com.edgesuite.net/8707/XS62ESP1.zip

This used to work so I do not know if the URL changed or if the updates.xml file changed. In either case can the updates.xml file be updated.

**Comment by dalgibbard** [comment]
First hint suggests that the URL provided by citric is wrong... Not much we can do to intervene there though.

**Comment by jyork-sarc** [comment]
I gave myself a workaround 
Created my own apache server copied the updates.xml file from citrix edited the file :1,$s/akdlm\///g saved then updated the patchurl in the patcher.py script and good to go.
