### ISSUE TITLE
Patch order?

### ISSUE THREAD

**Issue by jclendenan** [dalgibbard/citrix_xenserver_patcher#42]
I did a clean install of 6.5.0 and then ran the utility, and it did a great job, but i did notice it installed things in the following order:

SP1
SP1002
SP1004
SP1003
SP1005

I doubt it will be a major problem, as the RPM's should take care of this, but it would probably be best to do a sorted list of patches to allow "normal" dependency rules to work.

**Comment by dalgibbard** [comment]
I could have sworn that the patches are ordered... I'll need to check the method :)

**Comment by jclendenan** [comment]
It should be, but this seems to be in timestamp order, which may not always be true?  (re-releases?)
https://github.com/dalgibbard/citrix_xenserver_patcher/blob/master/patcher.py#L816

**Comment by dalgibbard** [comment]
One does wonder if (in terms of future patch releases) that this is perfectly acceptable? I don't see why Citrix would release a patch after another if it required strictly deploying prior to the one released before it (if that makes any degree of sense!). It would have to be assumed on Citrix's side that a customer may have applied the original patch before the new 'earlier' one is released, and would therefore have to be ensured for compatibility?

Guiding by timestamp largely avoids issues around Citrix's patch naming, which I believe may be the bigger risk to patch ordering?

I'm going to suggest leaving it as is; but I'm open to suggestions!

**Comment by jclendenan** [comment]
Agreed.  Leave as-is for the moment.  Others to advise if this becomes a problem.

**Comment by dalgibbard** [comment]
+1 - closing for now.
