### ISSUE TITLE
Exclusions file variable

### ISSUE THREAD

**Issue by LordMike** [dalgibbard/citrix_xenserver_patcher#44]
Hi,

It seems to me that the variable in the exclusions file (https://github.com/dalgibbard/citrix_xenserver_patcher/blob/master/exclusions/XS65_excludes.py#L2) should be named ´exclusions`, and not `autoexclusions`.. Else the patcher script won't interpret it correctly.

**Comment by dalgibbard** [comment]
Not quite; see lines 803 to 813:

```
## Request, where necessary, that patches in the Exclusions file are removed.
if not exclusions == False:
    for namelabel in exclusions:
        listremoveexclude(namelabel)

# Load the AutoExcludes:
autoexclusions = getAutoExcludeList(autourl)
## Patches loaded in from the auto-exclude file to be removed from the list next:    
if not autoexclusions == False:
    for namelabel in autoexclusions:
        listremoveexclude(namelabel)
```
This way, we allow for the definition of both a manual file _and_ the autofile, by defining and trimming the patchset list against the two separate lists.

ie.
* ```excludes``` = Manual/User exclusions
* ```autoexclusions``` = Automatically loaded exclusions from github

Hope that helps!

**Comment by LordMike** [comment]
The reason I investigated this was that the exclusions weren't being loaded. But perhaps I misunderstood a file placement og argument somewhere.. I can investigate later if necessary.

**Comment by dalgibbard** [comment]
If you like; post your command line and any additional files you're trying to load, and I can assist?

**Comment by LordMike** [comment]
Ooh. From reading the code, I see that the auto exclusions are fetched from the internet. 

I wanted to exclude a single update, since it didn't apply to my system (`XS65E015` iirc), so I added it to the exclusions file I had downloaded (I fetched the entire repo locally). 

As the update was not ignored, I had specified a file to be loaded using the switch, but to no help (as when specifying by switch it has to be the other variable name).. Hence my issue.

All solved :)

**Comment by dalgibbard** [comment]
Makes sense! If it helps; XS65E015 is also now excluded automatically :)

**Comment by dalgibbard** [comment]
Just went through the readme and this element isn't very clear. Will reopen this to update it.

**Comment by LordMike** [comment]
To be fair, I didn't read the Readme..

However, I don't know if it's because it wasn't there long ago ?.. I've
been using this patcher since 6.0. :)
Else. Shame on me.

Mvh.
Michael

**Comment by dalgibbard** [comment]
Documentation updated.
