### ISSUE TITLE
XS65ESP1016 not listed as an available update

### ISSUE THREAD

**Issue by forall** [dalgibbard/citrix_xenserver_patcher#48]
Hi,
Script not download the latest patch for XS65SP1 
Hotfix XS65ESP1016 - For XenServer 6.5.0 Service Pack 1 - https://support.citrix.com/article/CTX202619.

**Comment by thctlo** [comment]
I can confirm that this patch is missing, since its a security update, this should be a prio.

**Comment by thctlo** [comment]
I saw also the following, i have 2 server, 1 in production, 1 new installed now. 
After manualy, installing above, i see, also patch XS65E017 installed. 
Running patcher on the production server, i get no updates available. 
but it does say ( in the windows console ),  
not applied, : 
XS65E017  
XS65ESP1016

so these 2 are related.

**Comment by Daniel-Furcht** [comment]
These updates are not includes in the http://updates.xensource.com/XenServer/updates.xml.
Only see on http://support.citrix.com/article/CTX138115#XenServer 6.5.

**Comment by dalgibbard** [comment]
Seeing as though we're reliant on Citrix's RSS feed to deliver the list of pending updates, I'm not sure that there's much to do here.
I could probably code in a 'forced-includes', but that would involve some development effort which I don't currently have time for.
The URL always meets a particular format for downloading, so that shouldn't be a problem; ie:
```
http://support.citrix.com/filedownload/CTX202619/XS65ESP1016.zip
```

**Comment by Daniel-Furcht** [comment]
As a suggestion perhaps could keep a online list of updates on github.
This can be maintained by users.

**Comment by dalgibbard** [comment]
Indeed, it would be. The fiddly things for consideration are how we match these in with the other lists (Citrix RSS, auto exclusions, manual exclusions). ie:
* Where do we get the UUID from?
* How do we strip duplicates if the patch already exists in the Citrix RSS?
* Do 'manual-install' patches override exclusions files? If so, which ones, or both?

It's reasonably trivial I guess.

**Comment by Daniel-Furcht** [comment]
Before your script, i have for a time use another script (Dont rememb the source.). I have a sample for the file containig all parameter needed in the format:
XS62E015|c8b9d332-30e4-4e5e-9a2a-8aaae6dee91a|downloadns.citrix.com.edgesuite.net/akdlm/9279/XS62E015.zip|http://support.citrix.com/article/CTX140808

Patches manualy added from citrix support page, including UUID.

I wil test reaply existing patch, but i think this causes an return " Patch alredy applied" and dont causes any trouble.

**Comment by forall** [comment]
Hi,
Now script download XS65SP1016 and this  patch_url: http://support.citrix.com/filedownload/CTX202618/XS65E017.zip, so please add this patch to exclude list.

**Comment by dalgibbard** [comment]
Have updated the excludes list with all of the items in https://support.citrix.com/article/CTX203494

I'm suspecting that Citrix where holding off on adding 016 to the XML feed as they knew there was a cumulative patch coming up perhaps? I'm going to drop this ticket for now, as i'm not too keen on the idea of having to work around Citrix's shortfalls :)

Exclusions were updated in commit 1d675e3
