### ISSUE TITLE
6.0+ Exlusions not available

### ISSUE THREAD

**Issue by Meth0d007** [dalgibbard/citrix_xenserver_patcher#53]
Detected XenServer Version: 6.0.2

Failed to locate Auto Exclusions file: XS602_excludes.py
Checking for presence of Parent version file: XS60_excludes.py  ...

Failed to read Auto-Exclusion List from: https://raw.githubusercontent.com/dalgibbard/citrix_xenserver_patcher/master/exclusions/XS60_excludes.py
Check the URL is available, and connectivity is OK.

Error: HTTP Error 404: Not Found

NOTE: To proceed without downloading the Auto-Excludes file (not recommended), pass the "-E" flag.

**Comment by dalgibbard** [comment]
Yep, this seems expected- I've only provided exclusion files on what xenserver versions were current at the time of developing the script. I'll see what I can dig up from the XML, probably tomorrow.

**Comment by dalgibbard** [comment]
It's worth pointing out that with version 6.0.x you can use the XenCenter software to do patching with a free license; assuming they haven't changed it.

**Comment by dalgibbard** [comment]
Pushed auto exclusion files for v6.0 and v6.0.2.
