### ISSUE TITLE
Exclusion list for xenserver 6.1

### ISSUE THREAD

**Issue by goncalomsdias** [dalgibbard/citrix_xenserver_patcher#55]
I've been testing this patcher and on my xenserver 6.1 pool I can't get the list of available patches, because it fails to get auto-exclusion list from: https://raw.githubusercontent.com/dalgibbard/citrix_xenserver_patcher/master/exclusions/XS61_excludes.py

If I use the option -l -E the result is the same.

**Comment by dalgibbard** [comment]
I didn't know there was a 6.1, I hadn't checked! I've got lists for 6.0 6.0.1 6.2 and 6.5, but not 6.1 yet. I see 67 patches in total, so I'll try and evaluate these shortly and build an exclusion list for this version also.

**Comment by dalgibbard** [comment]
Have added - please give it a go and let me know how you get on! :)
