### ISSUE TITLE
Unauthorized Download XS65ESP1010.zip

### ISSUE THREAD

**Issue by alexandresavicki** [dalgibbard/citrix_xenserver_patcher#59]
A try aply the patches, but i receive this error:

Starting patching...

Downloading: XS65ESP1010.zip
...ERR: Failed to Download Patch!
Error: HTTP Error 401: Unauthorized

Here the URL that the script uses to make the dowload:
http://support.citrix.com/filedownload/CTX201974/XS65ESP1010.zip

**Comment by razerrazer** [comment]
I have the same problem ..

**Comment by dalgibbard** [comment]
Same patch? Are other patches affected? Maybe they've applied some sort of customer auth... I don't have any Citric Xenserver 6.x instances to hand at the moment, and am away until the new year :)

**Comment by krajster** [comment]
Citrix writes - Guest access will be removed in January 2017.

**Comment by dalgibbard** [comment]
Fun. That probably renders this project somewhat obsolete if they check licensing terms etc :) will have to look into it!

**Comment by vmpr** [comment]
meanwhile its a 404 ... if you need the file u can apply it manually from here: http://downloads.ebox.at/downloads/xen/xenserver-6.5/

**Comment by bkci** [comment]
I added a patch in the thread: [https://github.com/dalgibbard/citrix_xenserver_patcher/issues/60](url)

I have also created a pull request with pre-authentication functionality. I tested on my system and it was able to login and pull the latest patch down.

**Comment by dalgibbard** [comment]
Closed by #61
