### ISSUE TITLE
prompt to reboot breaks automated runs

### ISSUE THREAD

**Issue by ThisGuyCodes** [dalgibbard/citrix_xenserver_patcher#68]
when I run this in an automated manner (i.e. from ansible) and don't specify the "auto reboot" option, it prompts me to reboot at the end, which times out/breaks since there's no user to give input.

Could it be made to not prompt? Perhaps it makes sense to add this as a feature to the new (and amazing) -q flag?

**Comment by dalgibbard** [comment]
Yeap makes sense :) I'll sort this tomorrow.

**Comment by dalgibbard** [comment]
Or today lol

**Comment by dalgibbard** [comment]
Hey @ThisGuyCodes - this should be fixed in the master branch now, can you check and report back? :)

**Comment by ThisGuyCodes** [comment]
Beautiful! Actually broke me for a moment because I was using `expect`. Thanks again!
