### ISSUE TITLE
host-uuid not used any longer on xe cli

### ISSUE THREAD

**Issue by freerdp-github** [dalgibbard/citrix_xenserver_patcher#69]
Hi Guys, nice work on this script. The host-uuid parameter on the xe cli is no longer used. It is just host. If you look at [XS71E010](https://support.citrix.com/article/CTX224899) for example, on step 4, Citrix still has it wrong. Attempts to [tell Citrix about the error](https://discussions.citrix.com/topic/387204-please-fix-xe-cli-hotfix-updating-instructions-host-uuid-not-used/) have failed. I thought you would like to know.

Step 4 should be:
xe update-apply host=<hostname> uuid=<UUID_of_file>
xe upload-apply host=<hostname> uuid=<UUID_of_file>

Good luck

**Comment by dalgibbard** [comment]
I thought I'd fixed this already as part of #65 - did you run the script and get an error at a certain point?

**Comment by dalgibbard** [comment]
(Closing whilst awaiting an answer, as pretty sure this is a non-issue...)

**Comment by freerdp-github** [comment]
Yes, you are correct. This is fixed now, I was using a commit prior to #65. Thanks for the effort.

**Comment by dalgibbard** [comment]
Cool, no problem :)
