### ISSUE TITLE
Cannot download patches anymore

### ISSUE THREAD

**Issue by hingstarne** [dalgibbard/citrix_xenserver_patcher#76]
Dear all,

i tried to use your tool to patch my xenserver but it always fails to download the patches.

Starting patching...

Downloading: XS73E001.zip
...ERR: Failed to Download Patch!
Error: HTTP Error 404: Not Found

**Comment by dalgibbard** [comment]
Hi there,
Apologies for the delay.

@fetzerms has provided a pull request to fix this. Should be working fine now.
