### ISSUE TITLE
Hang on Internal Upload [bug]

### ISSUE THREAD

**Issue by Venomen** [dalgibbard/citrix_xenserver_patcher#79]
There is some problem with updating on for ex. xen7.0 and 7.2. After downloading file it just hang on internal upload:

```
Applying: XS72E002
Found unzipped patchfile: XS72E002.iso
Internal Upload...
```

I applied few patches via XenCenter but next patches still doesn't work and just hang on this. Although it's not a problem on xen6.5 :)

**Comment by dalgibbard** [comment]
Have a look at #72 and see if this fixes your issue :)

**Comment by Venomen** [comment]
@dalgibbard yeap, same issue ;)
