### ISSUE TITLE
SSL protocol problem

### ISSUE THREAD

**Issue by forall** [dalgibbard/citrix_xenserver_patcher#80]
Hi, 
I want to upgrade my XS 6.5 but from XS65ESP1010.zip I have eror message:

...ERR: Failed to Download Patch!
Error: <urlopen error (1, 'error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol')>

**Comment by dalgibbard** [comment]
I haven't used XenServer or updated this project in quite a while. My guess is that the upstream server has switched to being TLS1.2+ only or similar, and the old python/openssl versions baked into XS6.x probably doesn't support it - but I haven't checked if that's the case, just speculating.

If that is the issue, potential fixes would be to run a MITM proxy (to allow downgrade to a supported SSL/TLS version), or somehow deploy an updated python/openssl version on the hosts etc.

For what it's worth, XenServer 6.5 went end of life June 2018.

Closing as no further action possible on this end.
