### ISSUE TITLE
Does this support 8.1?

### ISSUE THREAD

**Issue by jbuseman-eng** [dalgibbard/citrix_xenserver_patcher#81]
I tried running the patcher on my XCP-ng pool master, but it gives the following output:

`Detected XenServer Version: 8.1.0

No Patches are currently installed.

Failed to read Auto-Exclusion List from: https://raw.githubusercontent.com/dalgibbard/citrix_xenserver_patcher/master/exclusions/XS81_excludes.py
Check the URL is available, and connectivity is OK.

Error: HTTP Error 404: Not Found

NOTE: To proceed without downloading the Auto-Excludes file (not recommended), pass the "-E" flag.`

Does this mean the patcher doesn't support 8.1?

**Comment by dalgibbard** [comment]
It usually means an exclusion list just doesn't exist... But I also haven't updated/maintained this in a few years now.

My suggestion would be to run it with ```-E``` to see what it says after that, and run it on a not-important box to test!

**Comment by vmpr** [comment]
hi @jbuseman-eng you don't need the patcher with xcp-ng, just do `yum update` on all pool members and reboot the master first, or use xenorchestra to update the pool - this tool is only for xenserver.

**Comment by jbuseman-eng** [comment]
> or use xenorchestra to update the pool - this tool is only for xenserver.

I'm not willing to pay for xenorchestra for my homelab and the premium trial expired so I can't update the pool anymore.

**Comment by vmpr** [comment]
you don't have to, use the compiled from sources version for free for your Home lab: https://xen-orchestra.com/docs/from_the_sources.html it has all features enable and I use it at home since a long time, works good. at work we have the payed ones.

**Comment by jbuseman-eng** [comment]
I will build it then. I assumed the source was the same as the free version after the trial.

**Comment by vmpr** [comment]
have fun with xoa from sources and you can close this issue now 👍
